model_list:
  - model_name: claude-opus-4-6
    litellm_params:
      model: openai/gpt-54-nano
      api_base: os.environ/AZURE_AI_API_BASE
      api_key: os.environ/AZURE_AI_API_KEY

  - model_name: claude-sonnet-4-6
    litellm_params:
      model: openai/gpt-54-nano
      api_base: os.environ/AZURE_AI_API_BASE
      api_key: os.environ/AZURE_AI_API_KEY

  - model_name: claude-haiku-4-5-20251001
    litellm_params:
      model: openai/gpt-54-nano
      api_base: os.environ/AZURE_AI_API_BASE
      api_key: os.environ/AZURE_AI_API_KEY

  - model_name: gpt-54-nano
    litellm_params:
      model: openai/gpt-54-nano
      api_base: os.environ/AZURE_AI_API_BASE
      api_key: os.environ/AZURE_AI_API_KEY

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY

litellm_settings:
  budget_duration: "30d"
  max_budget: 50
  use_chat_completions_url_for_anthropic_messages: true

alerting:
  - "webhook"

alert_webhook_url: "http://localhost:4001"
